namespace Cracker;

public enum FsmState
{
    CHECK_ARGUMENTS,
    BIND_CRYPT,
    READ_SHADOW,
    PREPARE_ALPHABET,
    PREPARE_THREAD_COUNTS,
    START_TIMER,
    RUN_CRACK,
    STOP_TIMER,
    NEXT_THREAD_COUNT,
    END_PROGRAM,
    ERROR
}